import '@/styles/globals.scss';
import RootLayout from '@/layout/RootLayout';
import Providers from '@/providers';
import type { Metadata } from 'next';
import localFont from 'next/font/local';

const geistSans = localFont({
    src: './fonts/GeistVF.woff',
    variable: '--font-geist-sans',
    weight: '100 900',
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function Layout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${geistSans.className}`}>
                <Providers>
                    <RootLayout>{children}</RootLayout>
                </Providers>
            </body>
        </html>
    );
}
